In [7]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Reshaping an array
matrix = arr.reshape(5, 1)
print("Reshaped Matrix:\n", matrix)

# Performing mathematical operations
arr_squared = arr ** 2
print("Squared Array:", arr_squared)

# Generating a random matrix
random_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", random_matrix)


Array: [1 2 3 4 5]
Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Squared Array: [ 1  4  9 16 25]
Random Matrix:
 [[0.48027518 0.97116906 0.90749652]
 [0.57457302 0.49921085 0.75261578]
 [0.86705718 0.50869352 0.34826314]]
